# Generated by Django 5.0.7 on 2024-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_uploadedfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
