# Generated by Django 5.0.7 on 2024-08-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_remove_user_address_remove_user_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
