# Generated by Django 5.0.7 on 2024-10-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_menu_options_remove_menu_menu_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
