# Generated by Django 5.0.7 on 2024-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_menu_unique_together_alter_menu_menu_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='allergy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='spicy',
            field=models.CharField(choices=[('0', '매운맛이 없는 음식'), ('1', '초보 (진라면 순한맛 맵기)'), ('2', '히수 (진라면 매운맛 맵기)'), ('3', '중수 (신라면 맵기)'), ('4', '고수 (불닭볶음면 맵기)'), ('5', '신 (핵불닭볶음면 맵기)')], default='0', max_length=50),
        ),
    ]
