# Generated by Django 5.0.7 on 2024-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='agent_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
