# Generated by Django 5.0.7 on 2024-10-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_menu_allergy_menu_menu_introduction_menu_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='spicy',
            field=models.CharField(choices=[('0', '매운맛이 없는 음식'), ('1', '초보 (진라면 순한맛 맵기)'), ('2', '하수 (진라면 매운맛 맵기)'), ('3', '중수 (신라면 맵기)'), ('4', '고수 (불닭볶음면 맵기)'), ('5', '신 (핵불닭볶음면 맵기)')], default='0', max_length=50),
        ),
    ]
