# Generated by Django 5.0.7 on 2024-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_notice_alter_menu_spicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
