# Generated by Django 5.0.7 on 2024-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
