# Generated by Django 5.0.7 on 2024-09-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_store_store_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_tel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
