# Generated by Django 5.0.7 on 2024-10-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_notice_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
