"""
Django settings for faq_backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from my_settings import SECRET_KEY, DATABASES
import os
from datetime import timedelta

# 프로젝트 내부 경로 설정
BASE_DIR = Path(__file__).resolve().parent.parent

# 개발 환경 설정 (프로덕션 환경에서는 적합하지 않음)
# 자세한 내용은 https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/ 참고

# 프로덕션 환경에서 사용할 경우 비밀키를 꼭 비밀로 유지할 것
SECRET_KEY = SECRET_KEY

# 프로덕션 환경에서 디버그 모드 사용 금지
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGIN_REDIRECT_URL = 'mypage'
LOGIN_URL = 'login'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 애플리케이션 정의

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'faq',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',
    'allauth.socialaccount.providers.google',
    'rest_framework',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = 'mypage'
LOGIN_URL = 'login'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # 추가된 미들웨어
]
SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id': 'bbde5c98ba159a907d6ccd4ce5f9ad96',  # 카카오 REST API 키
            'secret': '',  # 카카오는 secret이 필요 없습니다.
            'key': ''
        }
    },
    #  'naver': {
    #     'APP': {
    #         'client_id': 'Fz1x8vLnmERND8qBVuv_',  # 네이버 Client ID
    #         'secret': 'x5vyqX0Q9h',  # 네이버 Client Secret
    #         'key': ''
    #     }
    # }
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),  # Access Token의 유효 기간 (5분).
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Refresh Token의 유효 기간 (1일).
    'ROTATE_REFRESH_TOKENS': False,  # Refresh Token 사용 시 새 토큰 발급 여부 (False: 유지).
    'BLACKLIST_AFTER_ROTATION': True,  # Refresh Token 회전 시 이전 토큰 블랙리스트 추가 여부 (True).
    'ALGORITHM': 'HS256',  # JWT 서명 알고리즘 (HS256).
    'SIGNING_KEY': SECRET_KEY,  # JWT 서명에 사용될 비밀 키.
    'AUTH_HEADER_TYPES': ('Bearer',),  # JWT를 전송할 때 사용되는 Authorization 헤더 타입.
}


ROOT_URLCONF = 'faq_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'FAQ_Lean-AI_frontend', 'html')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'faq_backend.wsgi.application'

# 데이터베이스 설정
# 자세한 내용은 https://docs.djangoproject.com/en/5.0/ref/settings/#databases 참고

DATABASES = DATABASES

# 비밀번호 검증
# 자세한 내용은 https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators 참고

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 국제화 설정
# 자세한 내용은 https://docs.djangoproject.com/en/5.0/topics/i18n/ 참고

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False

# 정적 파일 설정 (CSS, JavaScript, Images)
# 자세한 내용은 https://docs.djangoproject.com/en/5.0/howto/static-files/ 참고

STATIC_URL = 'static/'

# 기본 기본 키 필드 유형
# 자세한 내용은 https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field 참고

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'