# Generated by Django 5.0.7 on 2024-11-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_public', '0002_public_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='faq_public.public_department'),
        ),
    ]
